const fs = require('fs');
const minifyHtml = require('html-minifier-terser').minify;
const parseCsv = require('csv-parse/lib/sync');
const template = require('lodash.template');

const HTML_TEMPLATE = fs.readFileSync('./templates/chart.template', 'utf8');
const createHtml = template(HTML_TEMPLATE, {
  interpolate: /<%=([\s\S]+?)%>/g,
  imports: {
    perMille: perMille,
    generatePerMilleData: generatePerMilleData,
    generateStateData: generateStateData,
  },
});

const csv = fs.readFileSync('./data/data.csv', 'utf8');

const records = parseCsv(csv, {
  columns: true,
});

const states = new Set();
const map = new Map();
let maxCount = 0;
let latestDate = '1970-01-01';
for (const {date, state, vaccinationsCumulative, vaccinationsPerMille} of records) {
  states.add(state);
  const count = Number(vaccinationsCumulative);
  if (count > maxCount) {
    maxCount = count;
  }
  if (date > latestDate) {
    latestDate = date;
  }
  const perMille = Number(vaccinationsPerMille);
  if (!map.has(date)) {
    map.set(date, new Map());
  }
  map.get(date).set(state, {
    cumulative: count,
    perMille: perMille,
  });
}

const formatter = new Intl.NumberFormat('en', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});
function perMille(state) {
  const latestEntries = map.get(latestDate);
  const latestStateEntries = latestEntries.get(state);
  const perMille = latestStateEntries.perMille;
  return formatter.format(perMille);
}

function generatePerMilleData() {
  const labels = [
    // '2021-01-05',
    // '2021-01-06',
    // '2021-01-07',
    ...map.keys(),
  ];
  const datasets = [
    // {
    //   name: 'Bavaria',
    //   type: 'line',
    //   values: [2.9,5.93,8.28],
    // },
  ];

  for (const state of states) { // Guarantee consistent ordering.
    const counts = [];
    for (const entry of map.values()) {
      const count = Number(entry.get(state).perMille.toFixed(2));
      counts.push(count);
    }
    datasets.push({
      name: state,
      type: 'line',
      values: counts,
    });
  }

  const data = {
    labels,
    datasets,
    // This is a workaround that effectively sets minY=0.
    // https://github.com/frappe/charts/issues/86
    yMarkers: [
      {
        label: '',
        value: 0,
        type: 'solid'
      },
    ],
  };
  const stringified = JSON.stringify(data, null, 2);
  return stringified;
}

function generateStateData(desiredState) {
  const labels = [
    // '2021-01-05',
    // '2021-01-06',
    // '2021-01-07',
    ...map.keys(),
  ];
  const datasets = [
    // {
    //   name: 'Bavaria',
    //   type: 'line',
    //   values: [77876, 82749, 84349],
    // },
  ];

  const counts = [];
  for (const entry of map.values()) {
    const count = entry.get(desiredState).cumulative;
    counts.push(count);
  }
  datasets.push({
    name: desiredState,
    type: 'line',
    values: counts,
  });

  const data = {
    labels,
    datasets,
    // This is a workaround that effectively sets minY and maxY.
    // https://github.com/frappe/charts/issues/86
    yMarkers: [
      {
        label: '',
        value: 0,
        type: 'solid'
      },
      {
        label: '',
        value: Math.round(maxCount * 1.05),
        type: 'solid'
      },
    ],
  };
  const stringified = JSON.stringify(data, null, 2);
  return stringified;
/*
{
  labels: [
    '2021-01-05',
    '2021-01-06',
    '2021-01-07',
  ],
  datasets: [
    {
      name: 'Bavaria',
      type: 'line',
      values: [77876, 82749, 84349],
    },
  ],
}
*/
}

const html = createHtml({
  states: states,
});
const minified = minifyHtml(html, {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: false,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: false,
  minifyCSS: true,
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeTagWhitespace: false,
  sortAttributes: true,
  sortClassName: true,
});
fs.writeFileSync('./index.html', minified);
